name: subscription-updater

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
    - name: start update
      run: |
        pip install requests
        python main.py
    - name: push changes to remote
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git pull
        git add -A
        if [ -z "$(git status --porcelain)" ]; then 
          echo "No changes"
        else 
          git commit -m "updated subscription"
          git push
        fi
